services:
  mongodb:
    container_name: mongodb
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - wanderlust-network

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - wanderlust-network

  backend:
    container_name: backend
    image: roshan7498/wanderlust-backend:${IMAGE_TAG:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - wanderlust-network

  frontend:
    container_name: frontend
    image: roshan7498/wanderlust-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wanderlust-network

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9-community
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_JAVAOPTS: "-Xms256m -Xmx256m"
      SONAR_CE_JAVAOPTS: "-Xms256m -Xmx256m"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - wanderlust-network

  jenkins:
    container_name: jenkins
    image: roshan7498/wanderlust-jenkins:latest
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
      - frontend
      - sonarqube
    networks:
      - wanderlust-network

volumes:
  mongodb-data:
    external: true
    name: wanderlust-mega-project_mongodb-data

  redis-data:
    external: true
    name: wanderlust-mega-project_redis-data

  jenkins_home:
    external: true
    name: wanderlust-mega-project_jenkins_home

  sonarqube_data:
    external: true
    name: sonarqube_data

  sonarqube_extensions:
    external: true
    name: sonarqube_extensions

networks:
  wanderlust-network:
    driver: bridge
